In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/imdb_top_1000_tv_episodes.csv", index_col="position")
df.head()

,episode_name,series_name,episode_number,airdate,duration,tv_rating,episode_rating,votes
position,,,,,,,,
1,Everyone's Waiting,Six Feet Under,S5.E12,2001–2005,1h 13m,TV-MA,9.9,(19K)
2,The View from Halfway Down,BoJack Horseman,S6.E15,2014–2020,26m,TV-MA,9.9,(33K)
3,End of the Prologue,Vinland Saga,S1.E24,2019–2023,24m,TV-MA,9.9,(42K)
4,"Sozin's Comet, Part 4: Avatar Aang",Avatar: The Last Airbender,S3.E21,2005–2008,21m,TV-Y7,9.9,(27K)
5,Plan and Execution,Better Call Saul,S6.E7,2015–2022,50m,TV-14,9.9,(87K)

In [3]:
df.tail()

,episode_name,series_name,episode_number,airdate,duration,tv_rating,episode_rating,votes
position,,,,,,,,
996,Episode #1.2,Brave and Beautiful,S1.E2,2016–2017,NaN,NaN,9.5,(1.7K)
997,Amarsi Un Pò,Master of None,S2.E9,2015–2021,57m,TV-MA,9.5,(3.1K)
998,"Crazy Diamond Is Unbreakable, Part 2",JoJo's Bizarre Adventure,S3.E38,2012–,23m,TV-14,9.5,(3.4K)
999,Islands Part 8: The Light Cloud,Adventure Time,S8.E27,2010–2018,11m,NaN,9.5,(1.8K)
1000,Cheer Up Pops,Regular Show,S8.E26,2010–2017,11m,TV-PG,9.5,(3.8K)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 1 to 1000
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   episode_name    1000 non-null   str
 1   series_name     1000 non-null   str
 2   episode_number  1000 non-null   str
 3   airdate         937 non-null    str
 4   duration        751 non-null    str
 5   tv_rating       645 non-null    str
 6   episode_rating  1000 non-null   float64
 7   votes           1000 non-null   str
dtypes: float64(1), str(7)
memory usage: 62.6 KB

In [5]:
episodes_rated_9_point_9_plus =  df[df["episode_rating"] >= 9.9]
episodes_rated_9_point_9_plus

,episode_name,series_name,episode_number,airdate,duration,tv_rating,episode_rating,votes
position,,,,,,,,
1,Everyone's Waiting,Six Feet Under,S5.E12,2001–2005,1h 13m,TV-MA,9.9,(19K)
2,The View from Halfway Down,BoJack Horseman,S6.E15,2014–2020,26m,TV-MA,9.9,(33K)
3,End of the Prologue,Vinland Saga,S1.E24,2019–2023,24m,TV-MA,9.9,(42K)
4,"Sozin's Comet, Part 4: Avatar Aang",Avatar: The Last Airbender,S3.E21,2005–2008,21m,TV-Y7,9.9,(27K)
5,Plan and Execution,Better Call Saul,S6.E7,2015–2022,50m,TV-14,9.9,(87K)
6,Re;,Code Geass: Lelouch of the Rebellion,S2.E25,2006–2008,24m,TV-14,9.9,(20K)
7,The Rains of Castamere,Game of Thrones,S3.E9,2011–2019,51m,TV-MA,9.9,(183K)
8,I Thought You'd Never Shut Up,Invincible,S3.E8,2021–,46m,TV-MA,9.9,(99K)
9,Don't Do Anything Rash,Invincible,S4.E7,2021–,53m,TV-MA,9.9,(51K)
10,Re:Zero kara Hajimaru Isekai Seikatsu,Re: Zero - Starting Life in Another World,S4.E11,2016–,NaN,NaN,9.9,(64K)
11,Omae wa Dare da,Re: Zero - Starting Life in Another World,S4.E8,2016–,NaN,NaN,9.9,(45K)
12,Battle of the Bastards,Game of Thrones,S6.E9,2011–2019,NaN,TV-MA,9.9,(309K)
13,The Winds of Winter,Game of Thrones,S6.E10,2011–2019,1h 8m,TV-MA,9.9,(228K)
14,A Regular Epic Final Battle,Regular Show,S8.E27,2010–2017,33m,TV-PG,9.9,(9.4K)
15,407 Proxy Authentication Required,Mr. Robot,S4.E7,2015–2019,56m,TV-MA,9.9,(47K)
16,Victory and Death,Star Wars: The Clone Wars,S7.E12,2008–2020,23m,TV-PG,9.9,(25K)

In [6]:
episodes_rated_9_point_9_plus["series_name"].value_counts()

series_name
Game of Thrones                              3
Invincible                                   2
Re: Zero - Starting Life in Another World    2
Six Feet Under                               1
BoJack Horseman                              1
Vinland Saga                                 1
Avatar: The Last Airbender                   1
Better Call Saul                             1
Code Geass: Lelouch of the Rebellion         1
Regular Show                                 1
Mr. Robot                                    1
Star Wars: The Clone Wars                    1
Name: count, dtype: int64

In [7]:
pd.DataFrame(
    episodes_rated_9_point_9_plus.sort_values(
    by="series_name",
    key=lambda s: s.map(s.value_counts()).drop(columns = ["position"]),
    ascending=False
)
.reset_index(drop=True))

,episode_name,series_name,episode_number,airdate,duration,tv_rating,episode_rating,votes
0,The Rains of Castamere,Game of Thrones,S3.E9,2011–2019,51m,TV-MA,9.9,(183K)
1,Battle of the Bastards,Game of Thrones,S6.E9,2011–2019,NaN,TV-MA,9.9,(309K)
2,The Winds of Winter,Game of Thrones,S6.E10,2011–2019,1h 8m,TV-MA,9.9,(228K)
3,I Thought You'd Never Shut Up,Invincible,S3.E8,2021–,46m,TV-MA,9.9,(99K)
4,Don't Do Anything Rash,Invincible,S4.E7,2021–,53m,TV-MA,9.9,(51K)
5,Re:Zero kara Hajimaru Isekai Seikatsu,Re: Zero - Starting Life in Another World,S4.E11,2016–,NaN,NaN,9.9,(64K)
6,Omae wa Dare da,Re: Zero - Starting Life in Another World,S4.E8,2016–,NaN,NaN,9.9,(45K)
7,Everyone's Waiting,Six Feet Under,S5.E12,2001–2005,1h 13m,TV-MA,9.9,(19K)
8,Plan and Execution,Better Call Saul,S6.E7,2015–2022,50m,TV-14,9.9,(87K)
9,Re;,Code Geass: Lelouch of the Rebellion,S2.E25,2006–2008,24m,TV-14,9.9,(20K)
10,End of the Prologue,Vinland Saga,S1.E24,2019–2023,24m,TV-MA,9.9,(42K)
11,"Sozin's Comet, Part 4: Avatar Aang",Avatar: The Last Airbender,S3.E21,2005–2008,21m,TV-Y7,9.9,(27K)
12,The View from Halfway Down,BoJack Horseman,S6.E15,2014–2020,26m,TV-MA,9.9,(33K)
13,A Regular Epic Final Battle,Regular Show,S8.E27,2010–2017,33m,TV-PG,9.9,(9.4K)
14,407 Proxy Authentication Required,Mr. Robot,S4.E7,2015–2019,56m,TV-MA,9.9,(47K)
15,Victory and Death,Star Wars: The Clone Wars,S7.E12,2008–2020,23m,TV-PG,9.9,(25K)

In [8]:
top_100 = df.iloc[0:100, :]
top_100.tail()

,episode_name,series_name,episode_number,airdate,duration,tv_rating,episode_rating,votes
position,,,,,,,,
96,Shattered,Star Wars: The Clone Wars,S7.E11,2008–2020,26m,TV-PG,9.8,(19K)
97,Where I Really Come From,Invincible,S1.E8,2021–,45m,TV-MA,9.8,(41K)
98,Perfect Game,Attack on Titan,S3.E16,2013–2023,24m,TV-MA,9.8,(121K)
99,Yusha,Attack on Titan,S3.E17,2013–2023,24m,TV-MA,9.8,(167K)
100,Hush,Buffy the Vampire Slayer,S4.E10,1997–2003,43m,TV-PG,9.7,(9.9K)

In [9]:
top_100["series_name"].value_counts()

series_name
Attack on Titan                              10
Re: Zero - Starting Life in Another World     6
One Piece                                     5
Game of Thrones                               4
Gintama                                       4
My Hero Academia                              4
BoJack Horseman                               3
Better Call Saul                              3
Invincible                                    3
Star Wars: The Clone Wars                     3
Gravity Falls                                 3
Hunter X Hunter                               3
Avatar: The Last Airbender                    2
Mr. Robot                                     2
Community                                     2
Breaking Bad                                  2
The Office                                    2
JoJo's Bizarre Adventure                      2
Heated Rivalry                                2
Person of Interest                            2
Legend of the Galactic Heroes                 2
Six Feet Under                                1
Vinland Saga                                  1
Code Geass: Lelouch of the Rebellion          1
Regular Show                                  1
SpongeBob SquarePants                         1
Doctor Who                                    1
Tomorrow's Joe                                1
The Mandalorian                               1
Clannad                                       1
Black Clover                                  1
Dexter                                        1
Demon Slayer: Kimetsu no Yaiba                1
Fighting Spirit: New Challenger               1
Kaguya-sama: Love Is War                      1
Succession                                    1
Bluey                                         1
Fighting Spirit                               1
Hannibal                                      1
It's Always Sunny in Philadelphia             1
Jujutsu Kaisen                                1
Dimension 20                                  1
Your Lie in April                             1
Rick and Morty                                1
Star Wars: Rebels                             1
The Amazing World of Gumball                  1
LazyTown                                      1
Violet Evergarden                             1
Adventure Time                                1
Steins;Gate 0                                 1
Chernobyl                                     1
Buffy the Vampire Slayer                      1
Name: count, dtype: int64

In [10]:
print(f"Number of Unique Series in Top 100 TV episodes is {top_100['series_name'].nunique()}")

Number of Unique Series in Top 100 TV episodes is 52

In [11]:
# Unique Number of Series in Top 100
anime = {
    "Attack on Titan",
    "Re: Zero - Starting Life in Another World",
    "One Piece",
    "Gintama",
    "My Hero Academia",
    "Hunter X Hunter",
    "JoJo's Bizarre Adventure",
    "Code Geass: Lelouch of the Rebellion",
    "Vinland Saga",
    "Tomorrow's Joe",
    "Clannad",
    "Black Clover",
    "Demon Slayer: Kimetsu no Yaiba",
    "Fighting Spirit",
    "Fighting Spirit: New Challenger",
    "Kaguya-sama: Love Is War",
    "Legend of the Galactic Heroes",
    "Jujutsu Kaisen",
    "Your Lie in April",
    "Steins;Gate 0",
    "Violet Evergarden"
}

western_animation = {
    "Avatar: The Last Airbender",
    "Invincible",
    "Star Wars: The Clone Wars",
    "Gravity Falls",
    "Regular Show",
    "SpongeBob SquarePants",
    "Bluey",
    "Rick and Morty",
    "Star Wars: Rebels",
    "The Amazing World of Gumball",
    "Adventure Time",
    "LazyTown",
    "BoJack Horseman"
}

live_action_sitcoms = {
    "Community",
    "The Office",
    "It's Always Sunny in Philadelphia"
}

live_action_series = {
    "Game of Thrones",
    "Better Call Saul",
    "Mr. Robot",
    "Breaking Bad",
    "Heated Rivalry",
    "Person of Interest",
    "Six Feet Under",
    "Doctor Who",
    "2022 FIFA World Cup Qatar",
    "The Mandalorian",
    "Dexter",
    "Succession",
    "Hannibal",
    "Dimension 20",
    "Chernobyl",
    "Buffy the Vampire Slayer"
}

In [12]:
def get_category(series):
    if series in anime:
        return "anime"
    elif series in western_animation:
        return "western_animation"
    elif series in live_action_sitcoms:
        return "live_action_sitcom"
    elif series in live_action_series:
        return "live_action_series"
    else:
        return "other"

top_100["category"] = top_100["series_name"].map(get_category)

In [13]:
top_100["category"].value_counts(normalize=True).mul(100).round(1).astype(str).add('%')

category
anime                 49.0%
live_action_series    24.0%
western_animation     22.0%
live_action_sitcom     5.0%
Name: proportion, dtype: str

In [14]:
# Re:Zero Episodes in Top 100 Episodes
top_100[top_100["series_name"] == "Re: Zero - Starting Life in Another World"]

,episode_name,series_name,episode_number,airdate,duration,tv_rating,episode_rating,votes,category
position,,,,,,,,,
10,Re:Zero kara Hajimaru Isekai Seikatsu,Re: Zero - Starting Life in Another World,S4.E11,2016–,NaN,NaN,9.9,(64K),anime
11,Omae wa Dare da,Re: Zero - Starting Life in Another World,S4.E8,2016–,NaN,NaN,9.9,(45K),anime
70,Kanshi-tô no Bannin,Re: Zero - Starting Life in Another World,S4.E3,2016–,NaN,NaN,9.8,(30K),anime
71,Zangai,Re: Zero - Starting Life in Another World,S4.E9,2016–,NaN,NaN,9.8,(41K),anime
72,Satsujin wa Kuse ni Naru,Re: Zero - Starting Life in Another World,S4.E10,2016–,NaN,NaN,9.8,(34K),anime
84,Kyouki no Sotogawa,Re: Zero - Starting Life in Another World,S1.E15,2016–,24m,NaN,9.8,(24K),anime

In [15]:
top_200 = df.iloc[0:200, :]
top_200.tail()

,episode_name,series_name,episode_number,airdate,duration,tv_rating,episode_rating,votes
position,,,,,,,,
196,Two Brothers,Attack on Titan,S4.E19,2013–2023,24m,TV-MA,9.7,(97K)
197,Episode #2.17,Kaan Sekban'la Alt Tarafi Bi' Talk Show,S2.E17,2020–,NaN,NaN,9.7,(1.7K)
198,Ace Kyuushutsu! Shirohige Saigo no Senchou Mei...,One Piece,S1.E481,1999–,24m,TV-14,9.7,(9.1K)
199,Hi wo mo Yakitsukusu Chikara: Akainu Hijou no ...,One Piece,S1.E482,1999–,24m,TV-14,9.7,(52K)
200,Kotae wo Sagashite: Hiken no Ace Senjou ni Shisu,One Piece,S1.E483,1999–,24m,TV-14,9.7,(60K)

In [16]:
print(f"Number of Unique Series in Top 200 TV episodes is {top_200['series_name'].nunique()}")

Number of Unique Series in Top 200 TV episodes is 91

In [17]:
top_200["series_name"].value_counts()

series_name
One Piece                                    15
Attack on Titan                              13
Asi                                          10
Re: Zero - Starting Life in Another World     7
Black Clover                                  6
                                             ..
Sons of Anarchy                               1
Supernatural                                  1
Grey's Anatomy                                1
Fullmetal Alchemist: Brotherhood              1
Kaan Sekban'la Alt Tarafi Bi' Talk Show       1
Name: count, Length: 91, dtype: int64

In [18]:
top_500 = df.iloc[0:500, :]
top_500.tail()

,episode_name,series_name,episode_number,airdate,duration,tv_rating,episode_rating,votes
position,,,,,,,,
496,Sorezore no Eranda Michi: Luffy vs Garp!,One Piece,S1.E480,1999–,NaN,TV-14,9.6,(7.7K)
497,Shokei Shikkou Meirei Kudaru: Houiheki wo Topp...,One Piece,S1.E474,1999–,NaN,TV-14,9.6,(7.6K)
498,Hisshi no Sakebi: Unmei o Kaeru Yuuki Aru Suubyou,One Piece,S1.E488,1999–,24m,TV-14,9.6,(8K)
499,Baelor,Game of Thrones,S1.E9,2011–2019,57m,TV-MA,9.6,(77K)
500,Shanks Kenzan! Choujou Sensou Tsui ni Shuuketsu,One Piece,S1.E489,1999–,24m,TV-14,9.6,(8K)

In [19]:
print(f"Number of Unique Series in Top 500 TV episodes is {top_500['series_name'].nunique()}")

Number of Unique Series in Top 500 TV episodes is 157

In [20]:
top_500["series_name"].value_counts()

series_name
One Piece           47
Asi                 29
Gönülçelen          25
Gintama             18
Under the Trees     17
                    ..
Gullak               1
The Boys             1
The Last Kingdom     1
Odd Taxi             1
Curious George       1
Name: count, Length: 157, dtype: int64

In [21]:
top_1000 = df.iloc[0:1000, :]
top_1000.tail()

,episode_name,series_name,episode_number,airdate,duration,tv_rating,episode_rating,votes
position,,,,,,,,
996,Episode #1.2,Brave and Beautiful,S1.E2,2016–2017,NaN,NaN,9.5,(1.7K)
997,Amarsi Un Pò,Master of None,S2.E9,2015–2021,57m,TV-MA,9.5,(3.1K)
998,"Crazy Diamond Is Unbreakable, Part 2",JoJo's Bizarre Adventure,S3.E38,2012–,23m,TV-14,9.5,(3.4K)
999,Islands Part 8: The Light Cloud,Adventure Time,S8.E27,2010–2018,11m,NaN,9.5,(1.8K)
1000,Cheer Up Pops,Regular Show,S8.E26,2010–2017,11m,TV-PG,9.5,(3.8K)

In [22]:
print(f"Number of Unique Series in Top 1000 TV episodes is {top_1000['series_name'].nunique()}")

Number of Unique Series in Top 1000 TV episodes is 266

In [23]:
top_1000["series_name"].value_counts()

series_name
One Piece                              83
Gintama                                35
Asi                                    31
Gönülçelen                             31
Brave and Beautiful                    30
                                       ..
Line of Duty                            1
One Punch Man                           1
The Punisher                            1
My Little Pony: Friendship Is Magic     1
Master of None                          1
Name: count, Length: 266, dtype: int64

In [24]:
series_metadata = pd.read_csv("data/series_metadata.csv")
series_metadata.head()

,series_name,tmdb_id,genre_ids,genres,origin_country,original_language,first_air_date,overview,keywords
0,Vinland Saga,88803,"[16, 10768, 10759, 18]","['Animation', 'War & Politics', 'Action & Adve...",['JP'],ja,2019-07-08,"For a thousand years, the Vikings have made qu...","['swordplay', 'vandalism', 'mercenary', 'explo..."
1,Avatar: The Last Airbender,82452,"[10759, 18, 10751, 10765]","['Action & Adventure', 'Drama', 'Family', 'Sci...",['US'],en,2024-02-22,A young boy known as the Avatar must master th...,"['saving the world', 'monk', 'child hero', 're..."
2,Better Call Saul,60059,"[80, 18]","['Crime', 'Drama']",['US'],en,2015-02-08,Six years before Saul Goodman meets Walter Whi...,"['new mexico', 'moral conflict', 'crooked lawy..."
3,Code Geass: Lelouch of the Rebellion,31724,"[16, 10765, 10759, 18]","['Animation', 'Sci-Fi & Fantasy', 'Action & Ad...",['JP'],ja,2006-10-05,Japan has been invaded and conquered by the Br...,"['ideology', 'war strategy', 'politics', 'mind..."
4,Game of Thrones,1399,"[10765, 18, 10759]","['Sci-Fi & Fantasy', 'Drama', 'Action & Advent...",['US'],en,2011-04-17,Seven noble families fight for control of the ...,"['based on novel or book', 'kingdom', 'dragon'..."

In [25]:
metadata_dict = (
    series_metadata
    .set_index("series_name")
    [["genres", "origin_country", "keywords"]]
    .to_dict("index")
)

In [26]:
def get_category(series_name):
    stats = metadata_dict.get(series_name)

    if stats is None:
        return "other"

    genres = str(stats["genres"])
    origin = str(stats["origin_country"])
    keywords = str(stats["keywords"]).lower()

    if "Animation" in genres:
        if "JP" in origin:
            return "anime"
        elif "CN" in origin:
            return "donghua"
        elif "US" in origin:
            return "american_animation"
        elif "GB" in origin:
            return "british_animation"
        elif "AU" in origin:
            return "australian_animation"
        elif "FR" in origin:
            return "french_animation"
        else:
            return "other_animation"
    elif "Sci-Fi & Fantasy" in genres:
        return "fantasy_show"
    elif "Drama" in genres:
        if "US" in origin:
            return "american_drama"
        elif "GB" in origin:
            return "british_drama"
        elif "CN" in origin:
            return "chinese_drama"
        elif "IN" in origin:
            return "indian_drama"
        elif "TR" in origin:
            return "turkish_drama"
        else:
            return "other_drama"
    elif "Kids" in genres:
        return "kids_show"
    elif "Talk" in genres:
        return "talk_show"
    elif "Reality" in genres:
        return "reality_show"
    elif "Documentary" in genres:
        return "documentary"
    elif "miniseries" in keywords:
        return "miniseries"
    elif "sitcom" in keywords:
        return "sitcom"
    else:
        return "other_live_action"

top_1000["category"] = top_1000["series_name"].map(get_category)

In [27]:
top_1000["category"].value_counts(normalize=True).mul(100).round(2).astype(str).add("%")

category
anime                   38.5%
american_drama          15.9%
turkish_drama           14.8%
american_animation      11.4%
fantasy_show             8.1%
sitcom                   3.0%
indian_drama             1.5%
chinese_drama            1.2%
other_drama              1.1%
donghua                  0.8%
australian_animation     0.7%
reality_show             0.7%
other_live_action        0.5%
talk_show                0.5%
british_drama            0.5%
documentary              0.3%
kids_show                0.2%
other                    0.2%
french_animation         0.1%
Name: proportion, dtype: str

In [29]:
top_1000[top_1000["category"] == "other_live_action"]

,episode_name,series_name,episode_number,airdate,duration,tv_rating,episode_rating,votes,category
position,,,,,,,,,
175,Borderline Forever,Scott the Woz,S5.E5,2017–,1h 4m,NaN,9.7,(1.5K),other_live_action
385,Community Table Read,Community: Webisodes,S9.E1,2009–2020,35m,NaN,9.6,(1.5K),other_live_action
741,Jail,Dave,S1.E10,2020–2023,28m,TV-MA,9.5,(2.1K),other_live_action
766,Dave,Dave,S2.E10,2020–2023,34m,TV-MA,9.5,(1.5K),other_live_action
857,Looking for Love,Dave,S3.E10,2020–2023,48m,TV-MA,9.5,(1.1K),other_live_action

In [30]:
top_1000.columns

Index(['episode_name', 'series_name', 'episode_number', 'airdate', 'duration',
       'tv_rating', 'episode_rating', 'votes', 'category'],
      dtype='str')

In [31]:
top_1000["genres"] = top_1000["series_name"].map(lambda x: metadata_dict.get(x, {}).get(x, {}).get("genres", []))

In [ ]:
def clean_genres(genres):
    if pd.isna(genres):
        return []

    # If genres is already a list
    if isinstance(genres, list):
        return genres

    # If stored as a string representation of a list
    if isinstance(genres, str):
        try:
            import ast
            parsed = ast.literal_eval(genres)

            if isinstance(parsed, list):
                return parsed

            return [parsed]
        except (ValueError, SyntaxError):
            # Handle comma-separated strings
            return [g.strip() for g in genres.split(",")]

    return []

position
1       []
2       []
3       []
4       []
5       []
        ..
996     []
997     []
998     []
999     []
1000    []
Name: genres, Length: 1000, dtype: object